name: Flutter Build APK (Manual)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Установка зависимостей, необходимых для Flutter
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev

      # Клонирование и настройка Flutter SDK вручную
      - name: Clone Flutter SDK
        run: git clone https://github.com/flutter/flutter.git --branch stable --depth 1

      - name: Set up PATH
        run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Run Flutter Doctor
        run: flutter doctor

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
